name: Generate Contribution Space Shooter Game

on:
  schedule:
    - cron: "0 0 * * *"    # runs daily at midnight UTC
  workflow_dispatch:         # allows manual trigger
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-game:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Generate Space Shooter Game
        uses: czl9707/gh-space-shooter@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          username: 'kvsp7'
          output-path: 'assets/shooting-game.gif'
          strategy: 'random'
